

# The namespace here should match the name given in `NAMESPACE_FOR_DYNACONF`
MYSITE:
  DEBUG: True
  SERVER: flaskdynaconf.com
  PORT: 6666
  MESSAGE: Dynaconf works like a charm with Flask and YAML
  TEST_RULE: '/yaml'

