

# The env here should match the name given in `ENV_FOR_DYNACONF`
MYSITE:
  DEBUG: True
  SERVER: flaskdynaconf.com
  PORT: 6666
  MESSAGE: Dynaconf works like a charm with Flask and YAML
  TEST_RULE: '/flask_with_yaml'

